---
title: "Software"

---



\

**Srirama Bhamidipati** is a contributor to GAMA since 2013 and is a GAMA evangelist. GAMA is developed by several teams under the umbrella of the IRD/UPMC international research unit UMMISCO.  (see www.gama-platform.org for more details).

\

\** Distributed here with permission.

\



## **GAMA ** - Agent-based Modeling Software (Free Software)


_GAMA_ is a modeling and simulation development environment for building spatially explicit agent-based simulations.

Multiple application domains : Use GAMA for whatever application domain you want.
High-level and Intuitive Agent-based language : Write your models easily using GAML, a high-level and intuitive agent-based language.
GIS and Data-Driven models : Instantiate agents from any dataset, including GIS data, and execute large-scale simulations (up to millions of agents).
Declarative user interface : Declare interfaces supporting deep inspections on agents, user-controlled action panels, multi-layer 2D/3D displays & agent aspects.

Its latest version, 1.8, can be freely downloaded or built from source, and comes pre-loaded with several models, tutorials and a complete on-line documentation.

Download the Latest Release for 
<ul>
<li> <a href = "https://github.com/gama-platform/gama/releases/tag/latest">  Windows 32/64</a> </li>
<li> <a href = "https://github.com/gama-platform/gama/releases/tag/latest">  Linux 32/64</a> </li>
<li> <a href = "https://github.com/gama-platform/gama/releases/tag/latest">  macOS</a> </li>

</ul>

\

\


