---
title: "Bengaluru Metro"
author: "Ravi Gadepalli" 
---

```{r echo=F}
knitr::opts_chunk$set(message = FALSE, warning = F, echo = F )
```


```{r echo=F, message=F, warning=FALSE}
library(magrittr)
library(dplyr)
library(tidyr)
library(dodgr)
library(sf)
library(readxl)
library(ggplot2)
library(RColorBrewer)
library(stplanr)
```

```{r allcode, cache=TRUE, echo=F, warning=F, message=F  }
Daily_Traffic_Movement_CST_Aug_2022 <- read_excel("../../Data/Daily Traffic Movement_CSC & CST_for the month of Aug 2022.xlsx",
                                                  sheet = "daily traffic movement_CST")





Daily_Traffic_Movement_CSC_Aug_2022 <- read_excel("../../Data/Daily Traffic Movement_CSC & CST_for the month of Aug 2022.xlsx")





dailyCSCAug2022 <- pivot_longer(data=Daily_Traffic_Movement_CSC_Aug_2022, cols = 3:53) %>%
  rename(Origin = STATION, Destination = name, trips = value) %>%
  group_by(DATETIME, Origin, Destination) %>%
  summarise(TOTtrips = sum(trips)) %>%
  separate(DATETIME,c("year", "month", "day", "fromHr", "toHr"), "-" )  %>%
  mutate(across(c(1,2,3,4,5),readr::parse_number), calendar = lubridate::ymd(paste(year, month, day, "-")), pair = paste(Origin, Destination, sep = "-")) %>%
  select(-c(1:3))



dailyCSTAug2022 <- pivot_longer(data=Daily_Traffic_Movement_CST_Aug_2022, cols = 3:53) %>%
  rename(Origin = STATION, Destination = name, trips = value) %>%
  group_by(DATETIME, Origin, Destination) %>%
  summarise(TOTtrips = sum(trips)) %>%
  separate(DATETIME,c("year", "month", "day", "fromHr", "toHr"), "-" )  %>%
  mutate(across(c(1,2,3,4,5),readr::parse_number), calendar = lubridate::ymd(paste(year, month, day, "-")), pair = paste(Origin, Destination, sep = "-")) %>%
  select(-c(1:3))

rm(Daily_Traffic_Movement_CST_Aug_2022)
rm(Daily_Traffic_Movement_CSC_Aug_2022)


# READ STATION LOCATIONS

latlong <- read.csv("../stationLatLong.csv")

# COMBINE STATION LAT LONG TO MATRIX OF TRIPS

csc <- dplyr::left_join(x= dailyCSCAug2022, y = latlong, by = c("Origin" = "abbrev")) %>%
  rename(from_long = long, from_lat = lat) %>%
  dplyr::left_join(x= ., y = latlong, by = c("Destination" = "abbrev")) %>%
  rename(to_long = long, to_lat = lat)

cst <- dplyr::left_join(x= dailyCSTAug2022, y = latlong, by = c("Origin" = "abbrev")) %>%
  rename(from_long = long, from_lat = lat) %>%
  dplyr::left_join(x= ., y = latlong, by = c("Destination" = "abbrev")) %>%
  rename(to_long = long, to_lat = lat)

csc %>% group_by(OBJECTID.x) %>%  arrange(OBJECTID.x) %>% filter(row_number ()==1) -> csc_from
csc %>% group_by(OBJECTID.y) %>%  arrange(OBJECTID.y) %>% filter(row_number ()==1) -> csc_to

csc %>% group_by(OBJECTID.x) %>%  arrange(OBJECTID.x) %>% filter(row_number ()==1) -> cst_from
csc %>% group_by(OBJECTID.y) %>%  arrange(OBJECTID.y) %>% filter(row_number ()==1) -> cst_to

#dist <- dodgr::dodgr_dists(metro_graph, from = dffrom[,c("from_long", "from_lat")],to = dfto[,c("to_long", "to_lat")])

#flows <- array (runif (5 * 3), dim = c (5, 3))


# find date - time combinations that have full 51*51 = 2601 od pairs
csc_2601units <- dailyCSCAug2022 %>%  
  mutate(weekday = lubridate::wday(calendar,label = T) ) %>%
  filter(  weekday %in% c('Mon', 'Tue', 'Wed' , 'Thu' , 'Fri')) %>%
  group_by(calendar, fromHr) %>%
  tally() %>% filter(n==2601) %>%
  mutate(uniqueid = paste(as.character(calendar), "-", fromHr, sep = "" ))
cst_2601units <- dailyCSTAug2022 %>%  
  mutate(weekday = lubridate::wday(calendar,label = T) ) %>%
  filter(  weekday %in% c('Mon', 'Tue', 'Wed' , 'Thu' , 'Fri')) %>%
  group_by(calendar,fromHr) %>%
  tally() %>% filter(n==2601) %>%
  mutate(uniqueid = paste(as.character(calendar), "-", fromHr, sep = "" ))


# find common date time
common_date_time_CSC <-  csc_2601units %>% filter(uniqueid %in%  intersect(csc_2601units$uniqueid, cst_2601units$uniqueid))
common_date_time_CST <-  cst_2601units %>% filter(uniqueid %in%  intersect(csc_2601units$uniqueid, cst_2601units$uniqueid))


# filter trips for common date times

CSC_common_date_time_tables <- dailyCSCAug2022 %>%
  mutate(uniqueid = paste(as.character(calendar), "-", fromHr, sep = "" )) %>%
  filter(uniqueid %in% common_date_time_CSC$uniqueid)

CST_common_date_time_tables <- dailyCSTAug2022 %>%
  mutate(uniqueid = paste(as.character(calendar), "-", fromHr, sep = "" )) %>%
  filter(uniqueid %in% common_date_time_CST$uniqueid)

# remove intermediate variables
rm(common_date_time_CSC, common_date_time_CST)
rm(csc_2601units, cst_2601units)

# check if there are all pairs of ods'
cs <- CSC_common_date_time_tables %>% group_by(calendar, fromHr) %>% tally()
ct <- CST_common_date_time_tables %>% group_by(calendar, fromHr) %>% tally()

# create a matrix for each hour
# install.packages("BiocManager")
# BiocManager::install("decoupleR")
library(decoupleR)

Hour_of_Day <- "6" # later make this a variable
Date_of_Month <- "2022-08-01" # later make this a a variable
filterID <- paste(as.character(Date_of_Month), "-", Hour_of_Day, sep = "" )


CST_common_date_time_tables %>% filter(uniqueid == filterID) %>%
  pivot_wider_profile(names_from = Destination, id_cols = Origin, values_from = TOTtrips, to_matrix = T) -> cst_matrix

CSC_common_date_time_tables %>% filter(uniqueid == filterID) %>%
  pivot_wider_profile(names_from = Destination, id_cols = Origin, values_from = TOTtrips, to_matrix = T) -> csc_matrix



```

```{r results = 'hide' }
# BUILD DODGR GRAPH
metro <- sf::st_read("../../Data/GIS/lines12.shp")
metro_graph <- weight_streetnet(metro, wt_profile = "foot" , id_col = "id", type_col = "highway",
                                wt_profile_file = "../../Data/GIS/wtp.json")
``` 

```{r echo=F}
sorted_stations <- latlong %>% arrange(abbrev) %>% mutate(OBJECTID = row_number())

from <- sorted_stations[,c("long", "lat")]
to <- sorted_stations[,c("long", "lat")]

df <- dodgr_flows_aggregate (graph = metro_graph, from = from, to = to, flows = cst_matrix, norm_sums = F)

sf_f <- dodgr::dodgr_to_sf(df)
# sf::st_write(sf_f, "CCcst6am.shp", delete_layer = T )


# PLOT NETWORK

# library (mapdeck)
# mapdeck (style = mapdeck_style ()) %>%
#   add_line (metro_graph, 
#             origin = c ("from_lon", "from_lat"),
#             destination = c ("to_lon", "to_lat"),
#             stroke_colour = "flow", stroke_width = "flow",
#             stroke_opacity = "flow",
#             palette = "matlab_like2", legend = TRUE)

# CONVERT PROJECTION

p_sf <- sf::st_transform(sf_f, crs = 3857)

#  TRY TO GET A BUFFER ON SF

buffer_f <- p_sf %>% st_buffer( ., dist = .$flow, singleSide = T)
# plot(buffer_f$geometry)

library(ggplot2)
library(geomtextpath)

# k <-ggplot(data=sf_f) + geom_sf(data=sf_f,aes( fill =  flow) ) +
#   geom_textsf(data=sf_f,aes(label = flow),  vjust = -0.8, size = 5)
# 
# k
# 
# 
# 
# g_sf <- st_transform(buffer_f, crs = 4326)
# g <-ggplot(data=g_sf) + geom_sf(data=g_sf,aes( fill =  flow) ) +
#   geom_textsf(data=g_sf,aes(label = flow),  vjust = -0.8, size = 4)
# 
# g


# plot(buffer_f[,"flow"])


# plotting works======
library(stplanr)

l_f <- line_bearing(sf_f, bidirectional = F)

buffer_f$angle <- l_f

 # ggplot() + geom_sf(data = buffer_f, aes(fill = flow)) +
 #  geom_sf_text(data = buffer_f, aes(label = round(flow,1), angle = ifelse(angle >=0,90-angle,abs(angle)-90),family="sans",size = 8))+
 #  
 #  
 #  scale_fill_gradient(
 #    
 #    low = "pink",
 #    high = "red",
 #    space = "Lab",
 #    na.value = "grey50",
 #    guide = "colourbar",
 #    aesthetics = "fill"
 #  ) +
 #  theme_bw()

 
library(mapview) 
library(RColorBrewer)
#buffer_f %>% select(flow) %>% mapview::mapview(zcol = "flow", col.regions=brewer.pal(9, "YlGn"))

# buffer_f %>% select(flow) %>% mapview::mapview(zcol = "flow", col.regions=brewer.pal(10,"Reds"), popup = F)
```

```{r}


 
 # add points
 stations <- st_as_sf(latlong, coords = c("long", "lat"), crs=4326)
 buffer_f %>% select(flow) %>% mapview::mapview(zcol = "flow", col.regions=list( "darkgreen"  , "lawngreen" , "yellow" , "orange", "red"), alpha.regions = 1,popup = F) + mapview(stations, cex = 2, label= "abbrev")

```

